AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function for Gmail Push Notifications

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment environment
  DynamoDBTableName:
    Type: String
    Description: DynamoDB table name

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub gmail-push-${Environment}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}/index/*
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: gmail-push-notifications
        - Key: ManagedBy
          Value: GitHubActions

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub gmail-push-${Environment}-lambda
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
          ENVIRONMENT: !Ref Environment
          # APNs Token-based Authentication (JWT tokens - modern approach)
          # These will need to be set manually in Lambda console after deployment:
          # APNS_TEAM_ID: Your Apple Developer Team ID (10 characters)
          # APNS_KEY_ID: Your APNs Key ID (10 characters) 
          # APNS_PRIVATE_KEY: Your P8 private key file content
          # APNS_BUNDLE_ID: Your app's bundle identifier
          APNS_TEAM_ID: ""
          APNS_KEY_ID: ""
          APNS_PRIVATE_KEY: ""
          APNS_BUNDLE_ID: ""
      FunctionUrlConfig:
        Cors:
          AllowMethods:
            - GET
            - POST
            - DELETE
            - OPTIONS
          AllowHeaders:
            - Content-Type
          AllowOrigins:
            - '*'
          MaxAge: 86400
        AuthType: NONE
      Code:
        ZipFile: |
          // Placeholder - actual code will be uploaded via deployment package
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ 
                message: 'Lambda function deployed successfully',
                environment: process.env.ENVIRONMENT
              })
            };
          };
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: gmail-push-notifications
        - Key: ManagedBy
          Value: GitHubActions

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*

  LambdaFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      SourceArn: "*"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunction}
      RetentionInDays: 30

Outputs:
  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub ${AWS::StackName}-LambdaFunctionName
  
  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaFunctionArn
  
  LambdaExecutionRoleArn:
    Description: Lambda execution role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaExecutionRoleArn
  
  LambdaFunctionUrl:
    Description: Lambda Function URL for HTTPS access
    Value: !GetAtt LambdaFunction.FunctionUrl
    Export:
      Name: !Sub ${AWS::StackName}-LambdaFunctionUrl